In [9]:
import numpy as np
from scipy.linalg import expm

m_B = 51.66 # mass of robot body (kg)
m_b = 2.44 # mass of ball (kg)
l = 0.69 # distance from ball COM to total COM (m)
I_b = 0.0174 # ball moment of inertia (kg-m^2)
r_b = 0.1058 # ball radius (m)
I_B = 12.59 # intertia of body wrt center of ball (kg-m^2)
mu_theta = 3.68 # theta viscous damping coefficient (N-m-s/rad)
mu_phi = 3.68 # phi viscous damping coefficient (N-m-s/rad)
dt = 0.01
g = 9.81

Gamma_1 = I_b + I_B + m_b * r_b**2 + m_B * r_b**2 + m_B * l**2
Gamma_2 = I_B + m_B * l**2

# Compute F, G, and H
F = Gamma_2 + m_B * r_b * l
G = Gamma_1 + 2 * m_B * r_b * l
H = Gamma_2**2 - Gamma_1 * Gamma_2 + m_B**2 * l**2 * r_b**2



A = np.array([
    [0, 0, 1, 0],
    [0, 0, 0, 1],
    [m_B**2 * l**2 * g * r_b / H, m_B**2 * l**2 * g * r_b / H, mu_theta * Gamma_2 / H, -mu_phi * F / H],
    [m_B * g * l * (F - G) / H, m_B * g * l * (F - G) / H, -mu_theta * (Gamma_2 + m_B * r_b * l) / H, mu_phi * G / H]
])

B = B = np.array([
    [0],
    [0],
    [F / H],
    [-G / H]
])

A_d = expm(A * dt)

# Compute B_d
B_d = np.linalg.inv(A) @ (A_d - np.eye(A.shape[0])) @ B

print("A_d:")
print(A_d)
print("B_d:")
print(B_d)


A_d:
[[ 9.93416130e-01 -6.58387018e-03  9.29177587e-03  7.32370464e-04]
 [ 7.71926109e-03  1.00771926e+00  7.81361823e-04  9.19024299e-03]
 [-1.24434437e+00 -1.24434437e+00  8.63580053e-01  1.36347520e-01]
 [ 1.46385376e+00  1.46385376e+00  1.50650651e-01  8.49382470e-01]]
B_d:
[[-0.11885416]
 [ 0.11885416]
 [-0.03884005]
 [ 0.0430263 ]]
